FLOW_AFTER_FILTER_humidity =0

BRIDGE_FLOW_humidity = (FLOW_AFTER_FILTER_humidity()*RECICULATED_AIR_dry_flow()+1000*COMBUSTION_generated_water()+COMBUSTION_AIR_dry_flow()*AMBIENT_HUMIDITY)/BRIDGE_FLOW_dry_flow()

FLOW_AFTER_FILTER_dry_flow = MILL_OUTLET_FLOW_dry_flow + AIR_INGRESS_FILTER
AIII_BACK_CONVERSTION_recombined_water = OUTPUT_MATERIAL_dry_flow()-MATERIAL_AFTER_CALCINER_dry_flow()
MILL_OUTLET_FLOW_dry_flow = BRIDGE_FLOW_dry_flow + AIR_INGRESS_MILL
MILL_OUTLET_FLOW_humidity = BRIDGE_FLOW_humidity*BRIDGE_FLOW_dry_flow + AMBIENT_HUMIDITY * AIR_INGRESS_MILL + 1000*(DISSOCIATION_water + DRYING_water)/MILL_OUTLET_FLOW_dry_flow

FLOW_AFTER_FILTER_humidity = ( ( MILL_OUTLET_FLOW_humidity * MILL_OUTLET_FLOW_dry_flow) + (AMBIENT_HUMIDITY *AIR_INGRESS_FILTER) -1000* AIII_BACK_CONVERSTION_recombined_water ) / FLOW_AFTER_FILTER_dry_flow
RECIRCULATION_HUMIDITY = FLOW_AFTER_FILTER_humidity






















 
